---
esphome:
  name: garage-door-pico

rp2040:
  board: rpipicow

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

safe_mode:

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

logger:
  level: DEBUG

output:
  # Built-in LED
  - platform: gpio
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
    id: LED

binary_sensor:
  # East Garage Door
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: false
    name: East Garage Door
    id: east_garage_door
    device_class: garage_door
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: east_garage_door
                - binary_sensor.is_on: west_garage_door
            then:
              - output.turn_on: LED
            else:
              - output.turn_off: LED

  # West Garage Door
  - platform: gpio
    pin:
      number: 3
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
      inverted: false
    name: West Garage Door
    id: west_garage_door
    device_class: garage_door
    filters:
      - delayed_on: 10ms
    disabled_by_default: false
    publish_initial_state: true
    on_state:
      then:
        - if:
            condition:
              or:
                - binary_sensor.is_on: east_garage_door
                - binary_sensor.is_on: west_garage_door
            then:
              - output.turn_on: LED
            else:
              - output.turn_off: LED
